# Atividade 2 — Exercícios de Limpeza, Transformação e Agrupamento de Dados

Responda as perguntas abaixo usando o dataset **emendas_tratamento.parquet**. o dataset pode ser baixado em https://drive.google.com/file/d/19ydA23-eboyiKxN29JL1EQWW4CplTiKg/view?usp=sharing.

Cada resposta deve ter:
- Uma célula de **código** com a solução
- Uma célula de **texto** (Markdown) com a sua interpretação do resultado

---
## Passo 0 — Importar pandas e carregar os dados

In [1]:
import pandas as pd

df = pd.read_parquet('/content/emendas_parlamentares.parquet')
df.head(1)

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos,Código da Emenda_1
0,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,ALVORADA - RS,4300604,ALVORADA,4300000,...,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,0,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,700000.0,0.0,0.0,0.0,690900.0,9100.0,Sem informação

## 1) Filtre apenas as emendas do ano de **2022** e mostre as 30 primeiras linhas. Em seguida responda: Quanta emendas foram registradas em 2022?

In [9]:
df_2022 = df[df['Ano da Emenda'] == 2022]
print(df_2022.shape[0])

6108

## 2) Filtre as emendas da região **Norte** que tenham `Valor Empenhado` maior que **500.000** e mostre as 5 primeiras linhas. Em seguida, responda: quantas emendas atendem a esses duas condições ao mesmo tempo?

In [12]:
df_norte_500 = df[(df['Região'] == ' Norte') & (df['Valor Empenhado'] > 500000)]
df_norte_500.head()

Empty DataFrame
Columns: [Código da Emenda, Ano da Emenda, Tipo de Emenda, Código do Autor da Emenda, Nome do Autor da Emenda, Número da emenda, Localidade de aplicação do recurso, Código Município IBGE, Município, Código UF IBGE, UF, Região, Código Função, Nome Função, Código Subfunção, Nome Subfunção, Código Programa, Nome Programa, Código Ação, Nome Ação, Código Plano Orçamentário, Nome Plano Orçamentário, Valor Empenhado, Valor Liquidado, Valor Pago, Valor Restos A Pagar Inscritos, Valor Restos A Pagar Cancelados, Valor Restos A Pagar Pagos, Código da Emenda_1]
Index: []

[0 rows x 29 columns]

In [13]:
print(df_norte_500.shape[0])

0

## 3) Filtre as emendas que são do estado de **SÃO PAULO** ou do estado do **RIO DE JANEIRO** e mostre quantas linhas cada estado possui. Em seguida, responda: Qual dos dois estados possui mais emendas e quantas são?

In [14]:
sp_rj = df[(df['UF'] == 'SÃO PAULO')| (df['UF'] == 'RIO DE JANEIRO')]['UF'].value_counts()
sp_rj

UF
SÃO PAULO         10435
RIO DE JANEIRO     6988
Name: count, dtype: int64

## 4) Na coluna `Código da Emenda`, substitua todos os valores `"Sem informação"` por `"Não disponível"`. Mostre a contagem de valores únicos da coluna antes e depois da substituição.

In [15]:
df['Código da  Emenda'] = df['Código da Emenda'].replace("Sem informação","Não disponível")
print(df['Código da Emenda'].value_counts())

Código da Emenda
Sem informação    17808
202341820007          2
202336610004          2
201833870003          2
201833870004          2
                  ...
201921520003          1
201921520002          1
201921520001          1
201930530018          1
201921520008          1
Name: count, Length: 70731, dtype: int64

## 5) Na coluna `Nome Função`, transforme todos os valores para que fiquem em letras maiúsculas. Confirme a alteração mostrando os valores únicos da coluna.

In [16]:
df['Nome Função'] = df['Nome Função'].str.upper()
print(df['Nome Função'].unique())

['URBANISMO' 'COMÉRCIO E SERVIÇOS' 'SAÚDE' 'EDUCAÇÃO' 'AGRICULTURA'
 'ASSISTÊNCIA SOCIAL' 'DESPORTO E LAZER' 'DEFESA NACIONAL' 'SANEAMENTO'
 'DIREITOS DA CIDADANIA' 'GESTÃO AMBIENTAL' 'CULTURA'
 'CIÊNCIA E TECNOLOGIA' 'SEGURANÇA PÚBLICA' 'ORGANIZAÇÃO AGRÁRIA'
 'COMUNICAÇÕES' 'ADMINISTRAÇÃO' 'HABITAÇÃO' 'INDÚSTRIA' 'TRABALHO'
 'MÚLTIPLO' 'TRANSPORTE' 'PREVIDÊNCIA SOCIAL' 'ENCARGOS ESPECIAIS'
 'RELAÇÕES EXTERIORES' 'ENERGIA' 'ESSENCIAL À JUSTIÇA']

## 6) Verifique quantas linhas duplicadas existem no dataset. Em seguida, remova as duplicatas e mostre quantas linhas sobraram.

In [17]:
print(df.shape[0])
df = df.drop_duplicates()
print(df.shape[0])

88659
88596

In [18]:
df.shape

(88596, 30)

## 7) Remova duplicatas considerando apenas as colunas `Código da Emenda` e `Município`. Quantas linhas sobraram? O resultado é diferente de quando removemos duplicatas do DataFrame inteiro?

In [21]:
df_novo = df.drop_duplicates(subset=['Código da Emenda', 'Município'])
df_novo.shape[0]

75744

## 8) Identifique quais colunas possuem valores nulos e quantos nulos cada uma tem. Em seguida, responda: qual é a coluna que possui maior número de valores nulos e quantos são?

In [29]:
df_nulos = df.isnull().sum()
df_nulos

Código da Emenda                          0
Ano da Emenda                             0
Tipo de Emenda                            0
Código do Autor da Emenda             15961
Nome do Autor da Emenda               15961
Número da emenda                          0
Localidade de aplicação do recurso        0
Código Município IBGE                     0
Município                                 0
Código UF IBGE                            0
UF                                        0
Região                                    0
Código Função                             0
Nome Função                               0
Código Subfunção                          0
Nome Subfunção                            0
Código Programa                           0
Nome Programa                             0
Código Ação                               0
Nome Ação                                 0
Código Plano Orçamentário                 0
Nome Plano Orçamentário                   0
Valor Empenhado                           0
Valor Liquidado                           0
Valor Pago                                0
Valor Restos A Pagar Inscritos            0
Valor Restos A Pagar Cancelados           0
Valor Restos A Pagar Pagos                0
Código da Emenda_1                        0
Código da  Emenda                         0
dtype: int64

## 9) Preencha os valores nulos da coluna `codigo do autor` com **-1** e os valores nulos da coluna `nome do autor da emenda` com "desconhecido" e confirme que não restaram nulos nessa coluna.

In [47]:
df['Código do Autor da Emenda'] = df['Código do Autor da Emenda'].fillna(-1)
df['Nome do Autor da Emenda'] = df['Nome do Autor da Emenda'].fillna("Desconhecido")

## 10) Verifique o tipo da coluna `Ano da Emenda`. Converta-a para **string** (`str`). Mostre o tipo antes e depois da conversão.

In [49]:
df['Ano da emenda'] = df['Ano da Emenda'].astype(str)

## 11) Converta a coluna `Valor Empenhado` para o tipo **float** (caso ainda não seja). Mostre o tipo após a conversão.

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 88596 entries, 0 to 88595
Data columns (total 30 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Código da Emenda                    88596 non-null  object
 1   Ano da Emenda                       88596 non-null  int64
 2   Tipo de Emenda                      88596 non-null  object
 3   Código do Autor da Emenda           72635 non-null  float64
 4   Nome do Autor da Emenda             72635 non-null  object
 5   Número da emenda                    88596 non-null  object
 6   Localidade de aplicação do recurso  88596 non-null  object
 7   Código Município IBGE               88596 non-null  object
 8   Município                           88596 non-null  object
 9   Código UF IBGE                      88596 non-null  int64
 10  UF                                  88596 non-null  object
 11  Região                              88596 non-null  object
 12  Código Função                       88596 non-null  object
 13  Nome Função                         88596 non-null  object
 14  Código Subfunção                    88596 non-null  object
 15  Nome Subfunção                      88596 non-null  object
 16  Código Programa                     88596 non-null  object
 17  Nome Programa                       88596 non-null  object
 18  Código Ação                         88596 non-null  object
 19  Nome Ação                           88596 non-null  object
 20  Código Plano Orçamentário           88596 non-null  object
 21  Nome Plano Orçamentário             88596 non-null  object
 22  Valor Empenhado                     88596 non-null  float64
 23  Valor Liquidado                     88596 non-null  float64
 24  Valor Pago                          88596 non-null  float64
 25  Valor Restos A Pagar Inscritos      88596 non-null  float64
 26  Valor Restos A Pagar Cancelados     88596 non-null  float64
 27  Valor Restos A Pagar Pagos          88596 non-null  float64
 28  Código da Emenda_1                  88596 non-null  object
 29  Código da  Emenda                   88596 non-null  object
dtypes: float64(7), int64(2), object(21)
memory usage: 21.0+ MB

## 12) Calcule o **total** de `Valor Pago` por **Região**. Quais são as duas regiões que mais receberam recursos?

In [ ]:
df_regiao = df.groupby('Região')['Valor Pago'].sum()
df_regiao

## 13) Calcule a **quantidade** de emendas por **Nome Função**. Mostre as 5 funções com mais emendas.

In [28]:
em_nome_func = df.groupby('Nome Função')['Código da Emenda'].count().sort_values(ascending=False)
em_nome_func.head()

Nome Função
SAÚDE                 37039
URBANISMO              8655
EDUCAÇÃO               8101
AGRICULTURA            4938
ENCARGOS ESPECIAIS     4610
Name: Código da Emenda, dtype: int64

## 14) Crie uma nova coluna chamada `Saldo a Pagar`. Ela deve ser o resultado da subtração entre a coluna `Valor Empenhado` e a coluna `Valor Pago`. Mostre as 5 primeiras linhas apenas com essas três colunas.

In [30]:
df['Saldo a Pagar'] = df['Valor Empenhado'] - df['Valor Pago']
df['Saldo a Pagar'].head()

/tmp/ipykernel_2663/466119667.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Saldo a Pagar'] = df['Valor Empenhado'] - df['Valor Pago']

0     700000.00
1     487500.00
2     100000.00
3     243750.00
4    1658333.94
Name: Saldo a Pagar, dtype: float64

## 15) Elimine a(s) coluna(s) do dataframe que eestá totalmente vazia.

In [50]:
df = df.drop(columns=['Código da Emenda_1'])

KeyError: "['Código da Emenda_1'] not found in axis"

## 16) Para finalizar, salve o DataFrame transformado em um arquivo no formato JSON.

In [46]:
df.to_json('df_transformado.json,index=False')